# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 'Push News'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */6 * * *' # 定义 cron 表达式
  watch:
    types: [started] # 定义star是自动发送



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: 'Install dependencies'
      run: pip install -r requirements.txt
    - name: '开始运行'
      run: python wyy.py   
